application: spartify
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/spartify.appcache
  static_files: static/spartify.appcache
  mime_type: text/cache-manifest
  upload: static/spartify.appcache
- url: /static
  static_dir: static
- url: /api/.*
  script: spartify.app
- url: /.*
  static_files: templates/index.html
  upload: templates/index.html
