USER_REPEAT_VOTE_WAIT = 600
# 48 hours
CACHE_DEFAULT_TIMEOUT = 172800
PARTY_QUEUE_PANIC = 4

ECHONEST_API_KEY = 'RVA3NJIGEZR6AQL1U'
ECHONEST_BASE_URL = 'http://developer.echonest.com/api/v4/'
ECHONEST_MAX_TRACKS_PER_ARTIST = 1
ECHONEST_MAX_SIMILAR_ARTIST = 3

SPOTIFY_BASE_URL = 'http://ws.spotify.com/'
